dist: xenial
language: node_js
node_js:
- 8.10.0
before_install:
- sudo add-apt-repository -y ppa:wine/wine-builds && sudo apt-get update && sudo apt-get install -y --install-recommends winehq-devel
cache:
  npm: true
script:
- npm run build
deploy:
  provider: releases
  script: .travis/pu.sh
  on:
    branch: master
    tags: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: release-builds/*.zip
  skip_cleanup: true
